
server:
  port: 8080
spring:
  application:
    name: franchises
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:

adapters:
  r2dbc:
    host: "${BD_HOST}"
    port: "${BD_PORT}"
    database: "${BD_DATABASE}"
    shema: "${BD_SHEMA}"
    username: "${BD_USERNAME}"
    password: "${BD_PASSWORD}"